name: listenable_future_builder
description: A general purpose Builder widget that allows you to do async work on controller initialization
version: 0.0.3-beta
homepage: https://github.com/MelbourneDeveloper/listenable_future_builder

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  austerity: ^1.1.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter: